package de.tudarmstadt.ukp.dkpro.tc.api.features;

import java.util.List;

import org.apache.uima.jcas.JCas;
import org.apache.uima.jcas.tcas.Annotation;

import de.tudarmstadt.ukp.dkpro.tc.exception.TextClassificationException;

/**
 * Common signature for feature extractors which extract their features from the entire document or
 * from a given focus annotation.
 * 
 */
public interface FocusAnnotationFeatureExtractor
{
    /**
     * Some feature extractors will require some specific number of annotations that is greater than
     * one.
     * 
     * @param view
     *            the current view of the document.
     * @param focusAnnotation
     *            the annotation for which to collect features (iff null, the features will be
     *            extracted from the document text)
     * @return a list of features generated by the extractor for the focus annotation/view.
     */
    public List<Feature> extract(JCas view, Annotation focusAnnotation)
        throws TextClassificationException;
}
