package de.tudarmstadt.ukp.dkpro.tc.api.features;

import java.util.List;

import org.apache.uima.jcas.JCas;

import de.tudarmstadt.ukp.dkpro.tc.api.exception.TextClassificationException;

/**
 * Common signature for feature extractors which extract their features from a pair of documents.
 * 
 * @author nico.erbs@gmail.com
 * 
 */
public interface PairFeatureExtractor
{
    /**
     * Extracts features from a pair of documents
     * 
     * @param view1
     *            First view to be processed
     * @param view2
     *            Second view to be processed
     * @return a list of features generated by the extractor for the documents.
     * @throws TextClassificationException
     */
    public List<Feature> extract(JCas view1, JCas view2)
        throws TextClassificationException;
}
