/*******************************************************************************
 * Copyright 2014
 * Ubiquitous Knowledge Processing (UKP) Lab
 * Technische Universität Darmstadt
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package de.tudarmstadt.ukp.dkpro.tc.api.features;

import java.util.List;

import org.apache.uima.jcas.JCas;

import de.tudarmstadt.ukp.dkpro.tc.api.exception.TextClassificationException;

/**
 * Common signature for feature extractors which extract their features from the entire document
 * (view). Feature extractors which require specific annotations from which to extract their
 * features, should not implement this interface.
 * 
 */
public interface DocumentFeatureExtractor
{

    /**
     * Extracts features from the document text of the given view.
     * 
     * @param view
     *            the current view of the document.
     * @return a list of features generated by the extractor for the document.
     */
    public List<Feature> extract(JCas view)
        throws TextClassificationException;

}
