package de.tudarmstadt.ukp.dkpro.tc.api.features;

import java.util.List;

import org.apache.uima.jcas.JCas;

import de.tudarmstadt.ukp.dkpro.tc.api.exception.TextClassificationException;
import de.tudarmstadt.ukp.dkpro.tc.type.TextClassificationUnit;

/**
 * Common signature for feature extractors which extract their features from the entire document or
 * from a given classification unit.
 * 
 */
public interface ClassificationUnitFeatureExtractor
{
    /**
     * Extract features from the classification unit within the given view.
     * 
     * @param view
     *            the current view of the document.
     * @param classificationUnit
     *            the annotation for which to collect features (iff null, the features will be
     *            extracted from the document text)
     * @return a list of features generated by the extractor for the classification unit/view.
     */
    public List<Feature> extract(JCas view, TextClassificationUnit classificationUnit)
        throws TextClassificationException;
}
