package de.tudarmstadt.ukp.dkpro.tc.api.features;

import java.util.List;

import org.apache.uima.jcas.JCas;
import org.apache.uima.jcas.tcas.Annotation;

import de.tudarmstadt.ukp.dkpro.tc.exception.TextClassificationException;

public interface FeatureExtractor
{
    /**
     * Some feature extractors will require some specific number of annotations that is greater than
     * one. Such extractors should not implement this interface.
     * 
     * @param view
     *          the current view of the document.
     * @param focusAnnotation
     *          the annotation for which to collect features.
     * @return a list of features generated by the extractor for the focus annotation.
     */
    public List<Feature> extract(JCas view, Annotation focusAnnotation)
        throws TextClassificationException;
}
